# Generated by Django 4.2 on 2023-04-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('signature', models.CharField(default='anonymous', max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
